package english.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: (timestamp generation disabled)
 */
public class createenrollment extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(20);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: createenroll-0000
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "createenroll-0000", "createenroll-0000.wav", "The enrollment process analyzes your voice to create a baseline that will be used for future verifications.\r\nThe process requires a minimum of 3 successful enrollments. Be sure to speak in a clear voice during the enrollment process."); 

		// phrase: createenroll-0001
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "createenroll-0001", "createenroll-0001.wav", "When you\'re ready to begin the enrollment process, press any key."); 

		// phrase: createenroll-0002
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "createenroll-0002", "createenroll-0002.wav", "When you\'re ready to continue the enrollment process, press any key."); 

		// phrase: createenroll-0003
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "createenroll-0003", "createenroll-0003.wav", "The enrollment was successful."); 

		// phrase: createenroll-0004
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "createenroll-0004", "createenroll-0004.wav", "The enrollment was not successful. Let\'s try that again."); 

		// phrase: createenroll-0005
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "createenroll-0005", "createenroll-0005.wav", "That completes the enrollment process for this phrase. You can now test the verification system.\r\nIf you would like to continue to the verification system, please press 1.\r\nIf you would like to improve the accuracy or your voice biometrics, and perform additional enrollments, please press 2."); 

		// phrase: createenroll-1002
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "createenroll-1002", "createenroll-1002.wav", "Only two enrollments"); 

		// phrase: createenroll-1001
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "createenroll-1001", "createenroll-1001.wav", "Only one enrollment"); 

		// phrase: createenroll-0006
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "createenroll-0006", "createenroll-0006.wav", "left to complete."); 

		// phrase: createenroll-1003
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "createenroll-1003", "createenroll-1003.wav", "There are still three enrollments"); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: (timestamp generation disabled)
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(createenrollment.PHRASE_MAP, phraseName));
	}
}
