package english.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 2018-NOV-08  04:49:22 PM
 */
public class createuser extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(8);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: createuser-0000
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "createuser-0000", "createuser-0000.wav", "It appears this is the first time you\'re calling. Let\'s create a VoiceIt profile for you and begin the enrollment process."); 

		// phrase: createuser-0001
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "createuser-0001", "createuser-0001.wav", "A VoiceIt profile has been created and associated with this telephone number. Future calls from this number will automatically associate with this profile."); 

		// phrase: createuser-0002
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "createuser-0002", "createuser-0002.wav", "Now that we have a profile, the next step is to complete the enrollment process. Let\'s do that now."); 

		// phrase: createuser-0010
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "createuser-0010", "createuser-0010.wav", "We were unable to create a VoiceIt profile."); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2018-NOV-09  10:17:14 AM
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(createuser.PHRASE_MAP, phraseName));
	}
}
