package english.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: (timestamp generation disabled)
 */
public class main extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(12);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: main-0000
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "main-0000", "main-0000.wav", "Hello and welcome to the VoiceIt demonstration program for Avaya Orchestration Designer."); 

		// phrase: main-0001
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "main-0001", "main-0001.wav", "Goodbye."); 

		// phrase: main-0010
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "main-0010", "main-0010.wav", "Please try again later."); 

		// phrase: main-0011
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "main-0011", "main-0011.wav", "There was a problem interacting with the VoiceIt biometric system."); 

		// phrase: main-0012
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "main-0012", "main-0012.wav", "Please check the logs for more information."); 

		// phrase: main-background
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "main-background", "clock-tick-short.wav", ""); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: (timestamp generation disabled)
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(main.PHRASE_MAP, phraseName));
	}
}
