package english.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 2018-NOV-08  07:28:59 PM
 */
public class record extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(4);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: record-0000
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "record-0000", "record-0000.wav", "After the tone, please say the phrase."); 

		// phrase: record-0001
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "record-0001", "record-0001.wav", "I\'m sorry, but I didn\'t catch that. Let\'s try this again."); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2018-NOV-12  08:02:58 AM
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(record.PHRASE_MAP, phraseName));
	}
}
