package english.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: 2018-NOV-08  06:57:19 PM
 */
public class verification extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(8);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: verify-0000
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "verify-0000", "verify-0000.wav", "We are about to begin the voice verification process. When you are ready, you will be told a phrase to repeat. After you have spoken the phrase, we\'ll find out if VoiceIt has successfully verified you."); 

		// phrase: verify-0001
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "verify-0001", "verify-0001.wav", "When you\'re ready to begin the verification process, press any key."); 

		// phrase: verify-0002
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "verify-0002", "verify-0002.wav", "You\'re voice was successfully analysed and you have been verified as the person associated with this telephone number."); 

		// phrase: verify-0003
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "verify-0003", "verify-0003.wav", "Your voice has been successfully analysed and you have failed verification.\r\nIf you are the person this telephone number is associated with, a failure can sometimes happen if you\'re speaking too softly or not clearly enough.\r\nIf you are not the person associated with this telephone number, the verification process is successful."); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: 2018-NOV-12  08:02:58 AM
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(verification.PHRASE_MAP, phraseName));
	}
}
