package english.phrasesets;

/**
 * This phraseset class will be automatically populated with data from the 
 * phraseset project file.  Manual edits should only be outside of the tag 
 * areas or overridden methods. 
 * Class created on: 
 * Last generated by Orchestration Designer at: (timestamp generation disabled)
 */
public class verification extends com.avaya.sce.runtime.Phraseset { 

	//{{START:CLASS:FIELDS
	private static final com.avaya.sce.runtime.Phraseset.PhraseMap PHRASE_MAP;
	//}}END:CLASS:FIELDS

	/**
	 * Static initializer
	 */
	static {
		//{{START:PHRASESET:STATIC

		// Create the phrase map, then populate with phrases
		PHRASE_MAP = new com.avaya.sce.runtime.Phraseset.PhraseMap(8);
		com.avaya.sce.runtime.Phrase phrase;

		// phrase: verify-0000
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "verify-0000", "verify-0000.wav", "You are about to begin the voice verification process. When prompted, please repeat the given phrase in a clear voice."); 

		// phrase: verify-0001
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "verify-0001", "verify-0001.wav", "When you\'re ready to begin the verification process, press any key."); 

		// phrase: verify-0002
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "verify-0002", "verify-0002.wav", "You have successfully verified."); 

		// phrase: verify-0003
		com.avaya.sce.runtime.Phraseset.addLocalPhrase(PHRASE_MAP, "verify-0003", "verify-0003.wav", "Verification failed, please try again."); 

		//}}END:PHRASESET:STATIC
	}
	/**
	 * Returns the Phrase with the given name.  To override the
	 * behavior and dynamically return a different Phrase object,
	 * override the method "hookGetPhrase(...)".
	 * 
	 * This method is generated automatically by the code generator
	 * and should not be manually edited.  Manual edits may be overwritten
	 * by the code generator.
	 * Last generated by Orchestration Designer at: (timestamp generation disabled)
	 * @see com.avaya.sce.runtime.Phraseset#getPhrase(String) 
	 */ 
	public com.avaya.sce.runtime.Phrase getPhrase(String phraseName) {
		return(getPhrase(verification.PHRASE_MAP, phraseName));
	}
}
