package flow.subflow.createuser;

import static java.util.AbstractMap.SimpleImmutableEntry;

import com.avaya.sce.runtimecommon.ITraceInfo;
import com.avaya.sce.runtimecommon.VariableName;

import static tech.topcat.od.utils.TomcatUtils.addProperty;

/**
 * A basic servlet which allows a user to define their code, generate
 * any output, and to select where to transition to next.
 * Last generated by Orchestration Designer at: (timestamp generation disabled)
 */
public class SaveProfileMap extends com.avaya.sce.runtime.BasicServlet {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: (timestamp generation disabled)
	 */
	public SaveProfileMap() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method allows for custom integration with other Java components.
	 * You may use Java for sophisticated logic or to integrate with custom
	 * connectors (i.e. JMS, custom web services, sockets, XML, JAXB, etc.)
	 *
	 * Any custom code added here should work as efficiently as possible to prevent delays.
	 * It's important to design your callflow so that the voice browser (Voice Portal/IR)
	 * is not waiting too long for a response as this can lead to a poor caller experience.
	 * Additionally, if the response to the client voice browser exceeds the configured
	 * timeout, the platform may throw an "error.badfetch". 
	 *
	 * Using this method, you have access to all session variables through the 
	 * SCESession object.
	 *
	 * The code generator will *** NOT *** overwrite this method in the future.
	 * Last generated by Orchestration Designer at: (timestamp generation disabled)
	 */
	public void servletImplementation(com.avaya.sce.runtimecommon.SCESession mySession) {
		String propertyFile = mySession.getParameter("tech.topcat.voiceit_tech.demo.PROPERTY_FILE");
		mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_DEBUG, String.format("Collected [%s] from parameter [tech.topcat.voiceit_tech.demo.PROPERTY_FILE]", propertyFile));
		String ani = mySession.getVariableField(flow.IProjectVariables.SESSION, flow.IProjectVariables.SESSION_FIELD_ANI).getStringValue();
		mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_DEBUG, String.format("Collected [%s] from [%s]", ani == null ? "" : ani, new VariableName(flow.IProjectVariables.SESSION, flow.IProjectVariables.SESSION_FIELD_ANI).toString()));
		String userId = mySession.getVariableField(flow.IProjectVariables.CREATE_USER_RESULT, flow.IProjectVariables.CREATE_USER_RESULT_FIELD_USER_ID).getStringValue(); 
		mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_DEBUG, String.format("Collected [%s] from [%s]", userId == null ? "" : userId, new VariableName(flow.IProjectVariables.CREATE_USER_RESULT, flow.IProjectVariables.CREATE_USER_RESULT_FIELD_USER_ID).toString()));
		mySession.getTraceOutput().writeln(ITraceInfo.TRACE_LEVEL_DEBUG, String.format("Persisting user id to file [%s]", propertyFile));
		addProperty(getServletContext(), new SimpleImmutableEntry<String, String>(ani, userId), propertyFile);
	}
	/**
	 * Builds the list of branches that are defined for this servlet object.
	 * This list is built automatically by defining Goto nodes in the call flow editor.
	 * It is the programmer's responsibilty to provide at least one enabled Goto.<BR>
	 *
	 * The user should override updateBranches() to determine which Goto that the
	 * framework will activate.  If there is not at least one enabled Goto item, 
	 * the framework will throw a runtime exception.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.  To modify the list
	 * of branches for the flow item, override:
	 *     <code>updateBranches(Collection branches, SCESession mySession)</code>
	 *
	 * @return a Collection of <code>com.avaya.sce.runtime.Goto</code>
	 * objects that will be evaluated at runtime.  If there are no gotos
	 * defined in the Servlet node, then this returns null.
	 * Last generated by Orchestration Designer at: (timestamp generation disabled)
	 */
	public java.util.Collection getBranches(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		com.avaya.sce.runtime.Goto aGoto = null;
		list = new java.util.ArrayList(1);

		aGoto = new com.avaya.sce.runtime.Goto("createuser-InformSuccess", 0, true, "Default");
		list.add(aGoto);

		return list;
	}
}
