/**
 * Last generated by Orchestration Designer at: 2018-NOV-08  06:30:44 PM
 */
package english.prompts;

public class CreateEnrollPromptWhenReady extends com.avaya.sce.runtime.Prompt {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Constructor for CreateEnrollPromptWhenReady.
	 */
	public CreateEnrollPromptWhenReady() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}


	/**
	 * This method is generated automatically and should not be manually edited
	 * To manually edit the prompt, override:
	 * void updatePrompt()
	 * Last generated by Orchestration Designer at: 2018-NOV-12  08:02:57 AM
	 */
	public void buildPrompt(){
		com.avaya.sce.runtime.Format format = null;
		com.avaya.sce.runtime.RenderHint hint = null;
		com.avaya.sce.runtime.MediaPage mediaPage = null;
		setBarginType(com.avaya.sce.runtimecommon.SCERT.BARGIN_SPEECH);
		setName("CreateEnrollPromptWhenReady");
		setOrder(com.avaya.sce.runtime.Prompt.STANDARD);

		// Prompt level 1
		setTimeout(1,8000);
		setBargin(1,true);

		if ( new com.avaya.sce.runtime.Condition( "condition", "phraseInfo:count", com.avaya.sce.runtime.Expression.INT_EQUAL, "0", false, null ).evaluate(getSession()) == true ) {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASESET,"createenrollment:createenroll-0001",false));
		}

		else {
			add(1, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.PHRASESET,"createenrollment:createenroll-0002",false));
		}

		// Prompt level 2
		setTimeout(2,8000);
		setBargin(2,true);

		format = new com.avaya.sce.runtime.Format();
		format.add("time","250ms");
		add(2, new com.avaya.sce.runtime.PromptElement(com.avaya.sce.runtime.PromptElement.XML_TAG_FULL,"break", format));

	}
}
