package flow;

/**
 * This interface is used to define the name of variables that are 
 * declared in the call flow.  All variables are defined as 
 * <code>public static final String</code>, which allows user-defined
 * code to reference variable names by the Java variable name.
 * Last generated by Orchestration Designer at: (timestamp generation disabled)
 */
public interface IProjectVariables {





	//{{START:PROJECT:VARIABLES
	/**
	 * This is a reserved block of variable name definitions.
	 * The variable names defined here can be used as the key
	 * to get the <code>com.avaya.sce.runtime.Variable</code>
	 * from the <code>SCESession</code> at runtime.<br>
	 * 
	 * For example, given a variable name <code>phoneNum</code>,
	 * user-defined code should access the variable in this format:<PRE>
	 *   Variable phNum = mySession.getVariable(IProjectVariables.PHONE_NUM);
	 *   if ( phNum != null ) {
	 *        // do something with the variable
	 *   }</PRE>
	 * 
	 * This block of code is generated automatically by Orchestration Designer and should not
	 * be manually edited as changes may be overwritten by future code generation.
	 * Last generated by Orchestration Designer at: (timestamp generation disabled)
	 */
	public static final String ENROLL__PASSPHRASE = "Enroll_Passphrase";
	public static final String AUTHENTICATION__SUCCESS = "Authentication_Success";
	public static final String VOICE_IT_USER = "VoiceItUser";
	public static final String AUTHENTICATE__PASSPHRASE = "Authenticate_Passphrase";
	public static final String ENROLLMENT_COUNT = "enrollmentCount";
	public static final String VOICE_IT_CREATE_ENROLLMENT = "VoiceItCreateEnrollment";
	public static final String TIME = "time";
	public static final String REDIRECTINFO = "redirectinfo";
	public static final String ENROLLMENT_REFRESH = "EnrollmentRefresh";
	public static final String VOICE_IT_DELETE_USER = "VoiceItDeleteUser";
	public static final String SESSION = "session";
	public static final String DD_LAST_EXCEPTION = "ddLastException";
	public static final String VOICE_IT_CREATE_USER = "VoiceItCreateUser";
	public static final String DATE = "date";
	public static final String VOICE_IT_AUTHENTICATION = "VoiceItAuthentication";
	public static final String VOICE_IT_DELETE_ENROLLMENT = "VoiceItDeleteEnrollment";
	public static final String DEMO_PASSWORD = "demoPassword";
	public static final String SHAREDUUI = "shareduui";
	public static final String VOICE_IT_ENROLLMENTS = "VoiceItEnrollments";
	public static final String DEMO_USER_ID = "demoUserId";
	public static final String DEMO__USERID__PROVIDER = "DEMO_USERID_PROVIDER";
	//}}END:PROJECT:VARIABLES
	//{{START:PROJECT:VARIABLEFIELDS
	public static final String ENROLL__PASSPHRASE_FIELD_CONFIDENCE = "confidence";
	public static final String ENROLL__PASSPHRASE_FIELD_DURATION = "duration";
	public static final String ENROLL__PASSPHRASE_FIELD_MAXTIME = "maxtime";
	public static final String ENROLL__PASSPHRASE_FIELD_SIZE = "size";
	public static final String ENROLL__PASSPHRASE_FIELD_TERMCHAR = "termchar";
	public static final String ENROLL__PASSPHRASE_FIELD_UTTERANCE = "utterance";
	public static final String ENROLL__PASSPHRASE_FIELD_VALUE = "value";
	public static final String AUTHENTICATION__SUCCESS_FIELD_CONFIDENCE = "confidence";
	public static final String AUTHENTICATION__SUCCESS_FIELD_INPUTMODE = "inputmode";
	public static final String AUTHENTICATION__SUCCESS_FIELD_INTERPRETATION = "interpretation";
	public static final String AUTHENTICATION__SUCCESS_FIELD_NOINPUTCOUNT = "noinputcount";
	public static final String AUTHENTICATION__SUCCESS_FIELD_NOMATCHCOUNT = "nomatchcount";
	public static final String AUTHENTICATION__SUCCESS_FIELD_UTTERANCE = "utterance";
	public static final String AUTHENTICATION__SUCCESS_FIELD_VALUE = "value";
	public static final String VOICE_IT_USER_FIELD_API__ERROR = "API_Error";
	public static final String VOICE_IT_USER_FIELD_IS_SUCCESS = "IsSuccess";
	public static final String VOICE_IT_USER_FIELD_RESPONSE_CODE = "ResponseCode";
	public static final String VOICE_IT_USER_FIELD_RESULT = "Result";
	public static final String AUTHENTICATE__PASSPHRASE_FIELD_CONFIDENCE = "confidence";
	public static final String AUTHENTICATE__PASSPHRASE_FIELD_DURATION = "duration";
	public static final String AUTHENTICATE__PASSPHRASE_FIELD_MAXTIME = "maxtime";
	public static final String AUTHENTICATE__PASSPHRASE_FIELD_SIZE = "size";
	public static final String AUTHENTICATE__PASSPHRASE_FIELD_TERMCHAR = "termchar";
	public static final String AUTHENTICATE__PASSPHRASE_FIELD_UTTERANCE = "utterance";
	public static final String AUTHENTICATE__PASSPHRASE_FIELD_VALUE = "value";
	public static final String VOICE_IT_CREATE_ENROLLMENT_FIELD_API__ERROR = "API_Error";
	public static final String VOICE_IT_CREATE_ENROLLMENT_FIELD_DETECTED_TEXT_CONFIDENCE = "DetectedTextConfidence";
	public static final String VOICE_IT_CREATE_ENROLLMENT_FIELD_DETECTED_VOICEPRINT_TEXT = "DetectedVoiceprintText";
	public static final String VOICE_IT_CREATE_ENROLLMENT_FIELD_ENROLLMENT_ID = "EnrollmentID";
	public static final String VOICE_IT_CREATE_ENROLLMENT_FIELD_IS_SUCCESS = "IsSuccess";
	public static final String VOICE_IT_CREATE_ENROLLMENT_FIELD_RESPONSE_CODE = "ResponseCode";
	public static final String VOICE_IT_CREATE_ENROLLMENT_FIELD_RESULT = "Result";
	public static final String TIME_FIELD_AUDIO = "audio";
	public static final String TIME_FIELD_HOUR = "hour";
	public static final String TIME_FIELD_MILLISECOND = "millisecond";
	public static final String TIME_FIELD_MINUTE = "minute";
	public static final String TIME_FIELD_SECOND = "second";
	public static final String TIME_FIELD_TIMEZONE = "timezone";
	public static final String REDIRECTINFO_FIELD_PRESENTATIONINFO = "presentationinfo";
	public static final String REDIRECTINFO_FIELD_REASON = "reason";
	public static final String REDIRECTINFO_FIELD_SCREENINGINFO = "screeninginfo";
	public static final String REDIRECTINFO_FIELD_URI = "uri";
	public static final String ENROLLMENT_REFRESH_FIELD_API__ERROR = "API_Error";
	public static final String ENROLLMENT_REFRESH_FIELD_ENROLLMENT_ID = "EnrollmentID";
	public static final String ENROLLMENT_REFRESH_FIELD_IS_SUCCESS = "IsSuccess";
	public static final String ENROLLMENT_REFRESH_FIELD_RESPONSE_CODE = "ResponseCode";
	public static final String ENROLLMENT_REFRESH_FIELD_RESULT = "Result";
	public static final String VOICE_IT_DELETE_USER_FIELD_API__ERROR = "API_Error";
	public static final String VOICE_IT_DELETE_USER_FIELD_IS_SUCCESS = "IsSuccess";
	public static final String VOICE_IT_DELETE_USER_FIELD_RESPONSE_CODE = "ResponseCode";
	public static final String VOICE_IT_DELETE_USER_FIELD_RESULT = "Result";
	public static final String SESSION_FIELD_AAI = "aai";
	public static final String SESSION_FIELD_ANI = "ani";
	public static final String SESSION_FIELD_CALLTAG = "calltag";
	public static final String SESSION_FIELD_CHANNEL = "channel";
	public static final String SESSION_FIELD_CHANNELTYPE = "channeltype";
	public static final String SESSION_FIELD_CONVERSEFIRST = "conversefirst";
	public static final String SESSION_FIELD_CONVERSESECOND = "conversesecond";
	public static final String SESSION_FIELD_CURRENTLANGUAGE = "currentlanguage";
	public static final String SESSION_FIELD_DNIS = "dnis";
	public static final String SESSION_FIELD_EXIT_CUSTOMER_ID = "exitCustomerId";
	public static final String SESSION_FIELD_EXIT_INFO_1 = "exitInfo1";
	public static final String SESSION_FIELD_EXIT_INFO_2 = "exitInfo2";
	public static final String SESSION_FIELD_EXIT_PREFERRED_PATH = "exitPreferredPath";
	public static final String SESSION_FIELD_EXIT_REASON = "exitReason";
	public static final String SESSION_FIELD_EXIT_TOPIC = "exitTopic";
	public static final String SESSION_FIELD_LASTERROR = "lasterror";
	public static final String SESSION_FIELD_MEDIATYPE = "mediatype";
	public static final String SESSION_FIELD_PROTOCOLNAME = "protocolname";
	public static final String SESSION_FIELD_PROTOCOLVERSION = "protocolversion";
	public static final String SESSION_FIELD_SESSIONID = "sessionid";
	public static final String SESSION_FIELD_SESSIONLABEL = "sessionlabel";
	public static final String SESSION_FIELD_SHAREDMODE = "sharedmode";
	public static final String SESSION_FIELD_UCID = "ucid";
	public static final String SESSION_FIELD_UUI = "uui";
	public static final String SESSION_FIELD_VIDEOBITRATE = "videobitrate";
	public static final String SESSION_FIELD_VIDEOCODEC = "videocodec";
	public static final String SESSION_FIELD_VIDEOENABLED = "videoenabled";
	public static final String SESSION_FIELD_VIDEOFARFMTP = "videofarfmtp";
	public static final String SESSION_FIELD_VIDEOFORMAT = "videoformat";
	public static final String SESSION_FIELD_VIDEOFPS = "videofps";
	public static final String SESSION_FIELD_VIDEOHEIGHT = "videoheight";
	public static final String SESSION_FIELD_VIDEONEARFMTP = "videonearfmtp";
	public static final String SESSION_FIELD_VIDEOWIDTH = "videowidth";
	public static final String SESSION_FIELD_VPCALLEDEXTENSION = "vpcalledextension";
	public static final String SESSION_FIELD_VPCONVERSEONDATA = "vpconverseondata";
	public static final String SESSION_FIELD_VPCOVERAGEREASON = "vpcoveragereason";
	public static final String SESSION_FIELD_VPCOVERAGETYPE = "vpcoveragetype";
	public static final String SESSION_FIELD_VPRDNIS = "vprdnis";
	public static final String SESSION_FIELD_VPREPORTURL = "vpreporturl";
	public static final String DD_LAST_EXCEPTION_FIELD_ERRORCODE = "errorcode";
	public static final String DD_LAST_EXCEPTION_FIELD_MESSAGE = "message";
	public static final String DD_LAST_EXCEPTION_FIELD_OBJECT = "object";
	public static final String DD_LAST_EXCEPTION_FIELD_STACKTRACE = "stacktrace";
	public static final String DD_LAST_EXCEPTION_FIELD_TYPE = "type";
	public static final String VOICE_IT_CREATE_USER_FIELD_API__ERROR = "API_Error";
	public static final String VOICE_IT_CREATE_USER_FIELD_IS_SUCCESS = "IsSuccess";
	public static final String VOICE_IT_CREATE_USER_FIELD_RESPONSE_CODE = "ResponseCode";
	public static final String VOICE_IT_CREATE_USER_FIELD_RESULT = "Result";
	public static final String DATE_FIELD_AUDIO = "audio";
	public static final String DATE_FIELD_DAYOFMONTH = "dayofmonth";
	public static final String DATE_FIELD_DAYOFWEEK = "dayofweek";
	public static final String DATE_FIELD_DAYOFWEEKNUM = "dayofweeknum";
	public static final String DATE_FIELD_DAYOFYEAR = "dayofyear";
	public static final String DATE_FIELD_MONTH = "month";
	public static final String DATE_FIELD_MONTHINYEAR = "monthinyear";
	public static final String DATE_FIELD_YEAR = "year";
	public static final String VOICE_IT_AUTHENTICATION_FIELD_API__ERROR = "API_Error";
	public static final String VOICE_IT_AUTHENTICATION_FIELD_DETECTED_TEXT_CONFIDENCE = "DetectedTextConfidence";
	public static final String VOICE_IT_AUTHENTICATION_FIELD_DETECTED_VOICEPRINT_TEXT = "DetectedVoiceprintText";
	public static final String VOICE_IT_AUTHENTICATION_FIELD_IS_SUCCESS = "IsSuccess";
	public static final String VOICE_IT_AUTHENTICATION_FIELD_RESPONSE_CODE = "ResponseCode";
	public static final String VOICE_IT_AUTHENTICATION_FIELD_RESULT = "Result";
	public static final String VOICE_IT_DELETE_ENROLLMENT_FIELD_API__ERROR = "API_Error";
	public static final String VOICE_IT_DELETE_ENROLLMENT_FIELD_IS_SUCCESS = "IsSuccess";
	public static final String VOICE_IT_DELETE_ENROLLMENT_FIELD_RESPONSE_CODE = "ResponseCode";
	public static final String VOICE_IT_DELETE_ENROLLMENT_FIELD_RESULT = "Result";
	public static final String SHAREDUUI_FIELD_ID = "id";
	public static final String SHAREDUUI_FIELD_VALUE = "value";
	public static final String VOICE_IT_ENROLLMENTS_FIELD_API__ERROR = "API_Error";
	public static final String VOICE_IT_ENROLLMENTS_FIELD_ENROLLMENT_ID = "EnrollmentID";
	public static final String VOICE_IT_ENROLLMENTS_FIELD_IS_SUCCESS = "IsSuccess";
	public static final String VOICE_IT_ENROLLMENTS_FIELD_RESPONSE_CODE = "ResponseCode";
	public static final String VOICE_IT_ENROLLMENTS_FIELD_RESULT = "Result";
	//}}END:PROJECT:VARIABLEFIELDS
}
