package flow;

/**
 * This is a special reserved class that is repsonsible for loading application 
 * variables as well as the forward to the actual first form of the application.<br>
 * This class should not be manually edited as changes may be overridden by the 
 * code generator.<br>
 * Last generated by Orchestration Designer at: 2018-NOV-07  07:53:26 AM
 */
public class Start extends com.avaya.sce.runtime.Entry {

	//{{START:CLASS:FIELDS
	//}}END:CLASS:FIELDS

	/**
	 * Default constructor
	 * Last generated by Orchestration Designer at: 2018-NOV-07  07:53:26 AM
	 */
	public Start() {
		//{{START:CLASS:CONSTRUCTOR
		super();
		//}}END:CLASS:CONSTRUCTOR
	}

	/**
	 * This method is generated automatically.  Any changes may be overwritten.
	 * Returns the submit object that will redirect application flow to the first
	 * form in the application.  This also adds various standard variables to the
	 * list of data to be submitted to the runtime variable table.
	 * Last generated by Orchestration Designer at: 2018-NOV-12  08:31:56 PM
	 * @return the Submit object that contains the standard variables and the first form
	 */
	public com.avaya.sce.runtime.Submit getSubmit(com.avaya.sce.runtimecommon.SCESession mySession) {
		com.avaya.sce.runtime.Submit submit = new com.avaya.sce.runtime.Submit("UseridLookup");
		return ( submit );
	}
	/**
	 * This method initializes the SCE session with the variables that
	 * are defined in the application.<BR>
	 * 
	 * This method is generated automatically and should not be manually
	 * edited because changes may be overwritten by future code 
	 * generation.
	 * Last generated by Orchestration Designer at: 2018-NOV-12  08:31:56 PM
	 */
	public void initializeVariables(com.avaya.sce.runtimecommon.SCESession session) {
		com.avaya.sce.runtimecommon.IVariable variable = null;
		String[] variableFields = null;

		variableFields = new String[] {
			IProjectVariables.VERIFICATION_READY_PROMPT_FIELD_COLUMN_0,
			IProjectVariables.VERIFICATION_READY_PROMPT_FIELD_CONFIDENCE,
			IProjectVariables.VERIFICATION_READY_PROMPT_FIELD_INPUTMODE,
			IProjectVariables.VERIFICATION_READY_PROMPT_FIELD_INTERPRETATION,
			IProjectVariables.VERIFICATION_READY_PROMPT_FIELD_NOINPUTCOUNT,
			IProjectVariables.VERIFICATION_READY_PROMPT_FIELD_NOMATCHCOUNT,
			IProjectVariables.VERIFICATION_READY_PROMPT_FIELD_UTTERANCE,
			IProjectVariables.VERIFICATION_READY_PROMPT_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.VERIFICATION_READY_PROMPT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.TIME_FIELD_AUDIO,
			IProjectVariables.TIME_FIELD_HOUR,
			IProjectVariables.TIME_FIELD_MILLISECOND,
			IProjectVariables.TIME_FIELD_MINUTE,
			IProjectVariables.TIME_FIELD_SECOND,
			IProjectVariables.TIME_FIELD_TIMEZONE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.TIME, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.REDIRECTINFO_FIELD_PRESENTATIONINFO,
			IProjectVariables.REDIRECTINFO_FIELD_REASON,
			IProjectVariables.REDIRECTINFO_FIELD_SCREENINGINFO,
			IProjectVariables.REDIRECTINFO_FIELD_URI };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.REDIRECTINFO, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.ALL_PHRASES_FIELD_API__ERROR,
			IProjectVariables.ALL_PHRASES_FIELD_CONTENT_LANGUAGE,
			IProjectVariables.ALL_PHRASES_FIELD_COUNT,
			IProjectVariables.ALL_PHRASES_FIELD_IS_SUCCESS,
			IProjectVariables.ALL_PHRASES_FIELD_MESSAGE,
			IProjectVariables.ALL_PHRASES_FIELD_RESPONSE_CODE,
			IProjectVariables.ALL_PHRASES_FIELD_STATUS,
			IProjectVariables.ALL_PHRASES_FIELD_TEXT,
			IProjectVariables.ALL_PHRASES_FIELD_TIME_TAKEN };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.ALL_PHRASES, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.SESSION_FIELD_AAI,
			IProjectVariables.SESSION_FIELD_ANI,
			IProjectVariables.SESSION_FIELD_CALLTAG,
			IProjectVariables.SESSION_FIELD_CHANNEL,
			IProjectVariables.SESSION_FIELD_CHANNELTYPE,
			IProjectVariables.SESSION_FIELD_CONVERSEFIRST,
			IProjectVariables.SESSION_FIELD_CONVERSESECOND,
			IProjectVariables.SESSION_FIELD_CURRENTLANGUAGE,
			IProjectVariables.SESSION_FIELD_DNIS,
			IProjectVariables.SESSION_FIELD_EXIT_CUSTOMER_ID,
			IProjectVariables.SESSION_FIELD_EXIT_INFO_1,
			IProjectVariables.SESSION_FIELD_EXIT_INFO_2,
			IProjectVariables.SESSION_FIELD_EXIT_PREFERRED_PATH,
			IProjectVariables.SESSION_FIELD_EXIT_REASON,
			IProjectVariables.SESSION_FIELD_EXIT_TOPIC,
			IProjectVariables.SESSION_FIELD_LASTERROR,
			IProjectVariables.SESSION_FIELD_MEDIATYPE,
			IProjectVariables.SESSION_FIELD_PROTOCOLNAME,
			IProjectVariables.SESSION_FIELD_PROTOCOLVERSION,
			IProjectVariables.SESSION_FIELD_SESSIONID,
			IProjectVariables.SESSION_FIELD_SESSIONLABEL,
			IProjectVariables.SESSION_FIELD_SHAREDMODE,
			IProjectVariables.SESSION_FIELD_UCID,
			IProjectVariables.SESSION_FIELD_UUI,
			IProjectVariables.SESSION_FIELD_VIDEOBITRATE,
			IProjectVariables.SESSION_FIELD_VIDEOCODEC,
			IProjectVariables.SESSION_FIELD_VIDEOENABLED,
			IProjectVariables.SESSION_FIELD_VIDEOFARFMTP,
			IProjectVariables.SESSION_FIELD_VIDEOFORMAT,
			IProjectVariables.SESSION_FIELD_VIDEOFPS,
			IProjectVariables.SESSION_FIELD_VIDEOHEIGHT,
			IProjectVariables.SESSION_FIELD_VIDEONEARFMTP,
			IProjectVariables.SESSION_FIELD_VIDEOWIDTH,
			IProjectVariables.SESSION_FIELD_VPCALLEDEXTENSION,
			IProjectVariables.SESSION_FIELD_VPCONVERSEONDATA,
			IProjectVariables.SESSION_FIELD_VPCOVERAGEREASON,
			IProjectVariables.SESSION_FIELD_VPCOVERAGETYPE,
			IProjectVariables.SESSION_FIELD_VPRDNIS,
			IProjectVariables.SESSION_FIELD_VPREPORTURL };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.SESSION, variableFields, null, session, false, true );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DATE_FIELD_AUDIO,
			IProjectVariables.DATE_FIELD_DAYOFMONTH,
			IProjectVariables.DATE_FIELD_DAYOFWEEK,
			IProjectVariables.DATE_FIELD_DAYOFWEEKNUM,
			IProjectVariables.DATE_FIELD_DAYOFYEAR,
			IProjectVariables.DATE_FIELD_MONTH,
			IProjectVariables.DATE_FIELD_MONTHINYEAR,
			IProjectVariables.DATE_FIELD_YEAR };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DATE, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CREATE_ENROLL_READY_PROMPT_FIELD_COLUMN_0,
			IProjectVariables.CREATE_ENROLL_READY_PROMPT_FIELD_CONFIDENCE,
			IProjectVariables.CREATE_ENROLL_READY_PROMPT_FIELD_INPUTMODE,
			IProjectVariables.CREATE_ENROLL_READY_PROMPT_FIELD_INTERPRETATION,
			IProjectVariables.CREATE_ENROLL_READY_PROMPT_FIELD_NOINPUTCOUNT,
			IProjectVariables.CREATE_ENROLL_READY_PROMPT_FIELD_NOMATCHCOUNT,
			IProjectVariables.CREATE_ENROLL_READY_PROMPT_FIELD_UTTERANCE,
			IProjectVariables.CREATE_ENROLL_READY_PROMPT_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CREATE_ENROLL_READY_PROMPT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.VOICE_VERIFICATION_RESULT_FIELD_API__ERROR,
			IProjectVariables.VOICE_VERIFICATION_RESULT_FIELD_CONFIDENCE,
			IProjectVariables.VOICE_VERIFICATION_RESULT_FIELD_IS_SUCCESS,
			IProjectVariables.VOICE_VERIFICATION_RESULT_FIELD_MESSAGE,
			IProjectVariables.VOICE_VERIFICATION_RESULT_FIELD_RESPONSE_CODE,
			IProjectVariables.VOICE_VERIFICATION_RESULT_FIELD_STATUS,
			IProjectVariables.VOICE_VERIFICATION_RESULT_FIELD_TEXT,
			IProjectVariables.VOICE_VERIFICATION_RESULT_FIELD_TEXT_CONFIDENCE,
			IProjectVariables.VOICE_VERIFICATION_RESULT_FIELD_TIME_TAKEN };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.VOICE_VERIFICATION_RESULT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.ENROLLMENTS_REMAINING, "0", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CREATE_ENROLLMENT_RESULT_FIELD_API__ERROR,
			IProjectVariables.CREATE_ENROLLMENT_RESULT_FIELD_CONTENT_LANGUAGE,
			IProjectVariables.CREATE_ENROLLMENT_RESULT_FIELD_CREATED_AT,
			IProjectVariables.CREATE_ENROLLMENT_RESULT_FIELD_ID,
			IProjectVariables.CREATE_ENROLLMENT_RESULT_FIELD_IS_SUCCESS,
			IProjectVariables.CREATE_ENROLLMENT_RESULT_FIELD_MESSAGE,
			IProjectVariables.CREATE_ENROLLMENT_RESULT_FIELD_RESPONSE_CODE,
			IProjectVariables.CREATE_ENROLLMENT_RESULT_FIELD_STATUS,
			IProjectVariables.CREATE_ENROLLMENT_RESULT_FIELD_TEXT,
			IProjectVariables.CREATE_ENROLLMENT_RESULT_FIELD_TEXT_CONFIDENCE,
			IProjectVariables.CREATE_ENROLLMENT_RESULT_FIELD_TIME_TAKEN };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CREATE_ENROLLMENT_RESULT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.USER_ID, "", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.GET_ENROLLMENTS_RESULT_FIELD_API__ERROR,
			IProjectVariables.GET_ENROLLMENTS_RESULT_FIELD_CONTENT_LANGUAGE,
			IProjectVariables.GET_ENROLLMENTS_RESULT_FIELD_COUNT,
			IProjectVariables.GET_ENROLLMENTS_RESULT_FIELD_CREATED_AT,
			IProjectVariables.GET_ENROLLMENTS_RESULT_FIELD_IS_SUCCESS,
			IProjectVariables.GET_ENROLLMENTS_RESULT_FIELD_MESSAGE,
			IProjectVariables.GET_ENROLLMENTS_RESULT_FIELD_RESPONSE_CODE,
			IProjectVariables.GET_ENROLLMENTS_RESULT_FIELD_STATUS,
			IProjectVariables.GET_ENROLLMENTS_RESULT_FIELD_TEXT,
			IProjectVariables.GET_ENROLLMENTS_RESULT_FIELD_TIME_TAKEN,
			IProjectVariables.GET_ENROLLMENTS_RESULT_FIELD_VOICE_ENROLLMENT_ID };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.GET_ENROLLMENTS_RESULT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variable = com.avaya.sce.runtime.SimpleVariable.createSimpleVariable(IProjectVariables.THRESHOLD__ENROLL, "3", null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_ERRORCODE,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_MESSAGE,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_OBJECT,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_STACKTRACE,
			IProjectVariables.DD_LAST_EXCEPTION_FIELD_TYPE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.DD_LAST_EXCEPTION, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CHECK_USER_EXISTS_RESULT_FIELD_API__ERROR,
			IProjectVariables.CHECK_USER_EXISTS_RESULT_FIELD_EXISTS,
			IProjectVariables.CHECK_USER_EXISTS_RESULT_FIELD_IS_SUCCESS,
			IProjectVariables.CHECK_USER_EXISTS_RESULT_FIELD_MESSAGE,
			IProjectVariables.CHECK_USER_EXISTS_RESULT_FIELD_RESPONSE_CODE,
			IProjectVariables.CHECK_USER_EXISTS_RESULT_FIELD_STATUS,
			IProjectVariables.CHECK_USER_EXISTS_RESULT_FIELD_TIME_TAKEN };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CHECK_USER_EXISTS_RESULT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.PHRASE_INFO_FIELD_COUNT,
			IProjectVariables.PHRASE_INFO_FIELD_PHRASE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.PHRASE_INFO, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.CREATE_USER_RESULT_FIELD_API__ERROR,
			IProjectVariables.CREATE_USER_RESULT_FIELD_CREATED_AT,
			IProjectVariables.CREATE_USER_RESULT_FIELD_IS_SUCCESS,
			IProjectVariables.CREATE_USER_RESULT_FIELD_MESSAGE,
			IProjectVariables.CREATE_USER_RESULT_FIELD_RESPONSE_CODE,
			IProjectVariables.CREATE_USER_RESULT_FIELD_STATUS,
			IProjectVariables.CREATE_USER_RESULT_FIELD_TIME_TAKEN,
			IProjectVariables.CREATE_USER_RESULT_FIELD_USER_ID };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.CREATE_USER_RESULT, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.SHAREDUUI_FIELD_ID,
			IProjectVariables.SHAREDUUI_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.SHAREDUUI, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.RECORDING_FIELD_CONFIDENCE,
			IProjectVariables.RECORDING_FIELD_DURATION,
			IProjectVariables.RECORDING_FIELD_MAXTIME,
			IProjectVariables.RECORDING_FIELD_SIZE,
			IProjectVariables.RECORDING_FIELD_TERMCHAR,
			IProjectVariables.RECORDING_FIELD_UTTERANCE,
			IProjectVariables.RECORDING_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.RECORDING, variableFields, null, session, false, false );
		session.putVariable(variable);

		variableFields = new String[] {
			IProjectVariables.ENROLLMENTS_COMPLETE_FIELD_CONFIDENCE,
			IProjectVariables.ENROLLMENTS_COMPLETE_FIELD_INPUTMODE,
			IProjectVariables.ENROLLMENTS_COMPLETE_FIELD_INTERPRETATION,
			IProjectVariables.ENROLLMENTS_COMPLETE_FIELD_NOINPUTCOUNT,
			IProjectVariables.ENROLLMENTS_COMPLETE_FIELD_NOMATCHCOUNT,
			IProjectVariables.ENROLLMENTS_COMPLETE_FIELD_UTTERANCE,
			IProjectVariables.ENROLLMENTS_COMPLETE_FIELD_VALUE };
		variable = com.avaya.sce.runtime.ComplexVariable.createComplexVariable(IProjectVariables.ENROLLMENTS_COMPLETE, variableFields, null, session, false, false );
		session.putVariable(variable);
	}
	/**
	 * This method returns the name of the application.
	 * Last generated by Orchestration Designer at: 2018-NOV-12  08:31:56 PM
	 */
	public String getEntryName() {
		return("VoiceItDemo");
	}
	/**
	 * This method returns a list of life cycle classes for Pluggable Connectors.
	 * Last generated by Orchestration Designer at: 2018-NOV-12  08:31:56 PM
	 */
	public java.util.Collection getPluggableLifeCycle() {
		java.util.ArrayList result = new java.util.ArrayList();
		return(result);
	}
	/**
	 * This method returns a list of VXML contributor classes for Pluggable Connectors.
	 * Last generated by Orchestration Designer at: 2018-NOV-12  08:31:56 PM
	 */
	public java.util.Collection getPluggableVXMLContrib() {
		java.util.ArrayList result = new java.util.ArrayList();
		return(result);
	}
	/**
	 * This method returns the root document for the application.
	 * This method is generated automatically and should not be modified
	 * because changes may be overwritten by future code generation.
	 * Last generated by Orchestration Designer at: 2018-NOV-12  08:31:56 PM
	 */
	public String getRootDoc() {
		return("AppRoot");
	}
	/**
	 * Builds the list of input parameters that are defined for this application 
	 * entry.  This list is built automatically by adding Input Parameter
	 * nodes to AppRoot in the call flow editor.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.
	 *
	 * @return a Collection of <code>java.lang.String</code> objects that
	 * are the names of parameters the application is expecting.
	 * If the AppRoot node does not have any input parameters, then 
	 * this returns an empty list
	 * Last generated by Orchestration Designer at: 2018-NOV-12  08:31:56 PM
	 */
	public java.util.Collection getInputParams(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		list = new java.util.ArrayList();

		return list;
	}
	/**
	 * Builds the list of capture expression that are defined for this application 
	 * entry.  This list is built automatically by adding Capture Expression
	 * items to AppRoot in the call flow editor.<BR>
	 *
	 * This method is generated automatically and changes to it may
	 * be overwritten next time code is generated.
	 *
	 * @return a Collection of <code>CaptureExpression</code> objects that
	 * specify the ECMA script expression and the Orchestration Designer 
	 * session variable that will store the captured result.
	 * If the AppRoot node does not have any capture expression items, then 
	 * this returns an empty list
	 * Last generated by Orchestration Designer at: 2018-NOV-12  08:31:56 PM
	 */
	public java.util.Collection getCaptureExpressions(com.avaya.sce.runtimecommon.SCESession mySession) {
		java.util.List list = null;
		list = new java.util.ArrayList();

		return list;
	}
}
