package english.grammars;

/**
 * This class is generated automatically.
 * Only exit this class for Dynamic External grammars and override the method String getURL().
 * Last generated by Orchestration Designer at: (timestamp generation disabled)
 */
public class anykeydtmf extends com.avaya.sce.runtime.Grammar {

    //{{START:CLASS:FIELDS
    //}}END:CLASS:FIELDS

    /**
    * Constructor for anykeydtmf.
    */
    public anykeydtmf() {
		//{{START:CLASS:CONSTRUCTOR
        super();
        setRootLanguage("en-us");
        setMode("dtmf");
        setBuiltin(false);
        setFileName("anykeydtmf.grxml");
        addColName("Column0");
		//}}END:CLASS:CONSTRUCTOR
    }

}

